"""Blocking resolver configuration.

dnscrypt-proxy in the gateway, upstream DoH over TCP through the profile's own
SOCKS5 exit — so DNS resolves from the same place the traffic exits, which is
what makes per-port residential IPs geo-consistent without EDNS Client Subnet.

Stamps are resolved on the *host* at sync time rather than letting the container
fetch a resolver list at startup: one less thing that can fail inside a
namespace whose only route is a proxy.
"""

from __future__ import annotations

import re
import urllib.request
from pathlib import Path

from . import paths

RESOLVERS_URL = "https://download.dnscrypt.info/resolvers-list/v3/public-resolvers.md"

# our name -> the entry name in public-resolvers.md
UPSTREAMS: dict[str, str] = {
    "google": "google",
    "cloudflare": "cloudflare",
    "quad9": "quad9-doh-ip4-port443-filter-pri",
    "mullvad": "mullvad-doh",
}
DEFAULT_UPSTREAM = "google"

BLOCKLISTS: dict[str, str] = {
    # Bare domains, and "example.com blocks example.com and subdomain.example.com
    # but not thiseexample.com" — exactly dnscrypt-proxy's bare-name rule, so it
    # feeds blocked_names with no conversion.
    "oisd-big": "https://big.oisd.nl/domainswild2",
    "oisd-small": "https://small.oisd.nl/domainswild2",
    "oisd-nsfw": "https://nsfw.oisd.nl/domainswild2",
}

LISTEN_ADDR = "127.0.0.2"  # 127.0.0.1 is taken by pasta/pod DNS
LISTEN_PORT = 53

_SECTION = re.compile(r"^##\s+(\S+)\s*$")
_STAMP = re.compile(r"^(sdns://\S+)\s*$")


def fetch_stamps(timeout: int = 30) -> dict[str, str]:
    """name -> sdns:// stamp, parsed from the published resolver list."""
    with urllib.request.urlopen(RESOLVERS_URL, timeout=timeout) as resp:  # noqa: S310
        text = resp.read().decode("utf-8", "replace")
    stamps: dict[str, str] = {}
    current: str | None = None
    for line in text.splitlines():
        if m := _SECTION.match(line):
            current = m.group(1)
        elif current and (m := _STAMP.match(line.strip())):
            stamps.setdefault(current, m.group(1))
    return stamps


def sync_stamps() -> dict[str, str]:
    """Cache the stamps we care about next to the blocklists."""
    wanted = set(UPSTREAMS.values())
    found = {k: v for k, v in fetch_stamps().items() if k in wanted}
    missing = wanted - set(found)
    out = paths.blocklists_dir() / "stamps.txt"
    out.write_text("".join(f"{k} {v}\n" for k, v in sorted(found.items())))
    if missing:
        raise RuntimeError(f"no stamp found for {sorted(missing)}; resolver list changed?")
    return found


def load_stamps() -> dict[str, str]:
    path = paths.blocklists_dir() / "stamps.txt"
    if not path.exists():
        return {}
    return dict(line.split(" ", 1) for line in path.read_text().splitlines() if " " in line)


def fetch_blocklist(name: str, timeout: int = 120) -> Path:
    url = BLOCKLISTS.get(name)
    if not url:
        raise KeyError(f"unknown blocklist {name!r}")
    dest = paths.blocklists_dir() / f"{name}.txt"
    tmp = dest.with_suffix(".tmp")
    with urllib.request.urlopen(url, timeout=timeout) as resp:  # noqa: S310
        tmp.write_bytes(resp.read())
    if tmp.stat().st_size < 1024:
        tmp.unlink(missing_ok=True)
        raise RuntimeError(f"blocklist {name} came back suspiciously small")
    tmp.replace(dest)
    return dest


def merged_blocklist(names: list[str]) -> Path:
    """One file for the container to read, so the config never varies."""
    out = paths.blocklists_dir() / "blocked-names.txt"
    seen: set[str] = set()
    lines: list[str] = []
    for name in names:
        path = paths.blocklists_dir() / f"{name}.txt"
        if not path.exists():
            continue
        for raw in path.read_text(errors="replace").splitlines():
            entry = raw.strip()
            if not entry or entry.startswith(("#", "!")):
                continue
            if entry not in seen:
                seen.add(entry)
                lines.append(entry)
    out.write_text("\n".join(lines) + "\n")
    return out


def toml_config(upstream: str, *, blocklist: str, forwarder: str, forwarder_port: int) -> str:
    """dnscrypt-proxy config. `proxy` + `force_tcp` is the documented way to run
    over a SOCKS5 that carries no UDP."""
    stamps = load_stamps()
    name = UPSTREAMS.get(upstream, UPSTREAMS[DEFAULT_UPSTREAM])
    stamp = stamps.get(name)
    if not stamp:
        raise RuntimeError(f"no cached stamp for {name!r}; run `kiwi-fox dns sync` first")
    return f"""# generated by kiwi-fox — do not edit
listen_addresses = ['{LISTEN_ADDR}:{LISTEN_PORT}']
max_clients = 64
ipv4_servers = true
ipv6_servers = false
dnscrypt_servers = false
doh_servers = true
odoh_servers = false
require_dnssec = false
require_nolog = false
require_nofilter = false
server_names = ['{name}']

# Every query leaves through this profile's own exit, over TCP because SOCKS5
# carries no UDP. The gateway firewall is the guarantee, not this setting: a
# query that tries to go direct is dropped, never leaked.
proxy = 'socks5://{forwarder}:{forwarder_port}'
force_tcp = true

timeout = 7000
keepalive = 30
cache = true
cache_size = 4096
cache_min_ttl = 600
cache_max_ttl = 86400
cache_neg_min_ttl = 60
cache_neg_max_ttl = 600

block_ipv6 = true
blocked_query_response = 'refused'

[blocked_names]
blocked_names_file = '{blocklist}'

[static.'{name}']
stamp = '{stamp}'
"""
